### ISSUE TITLE
用法？

### ISSUE THREAD

**Issue by catbb49294929** [cosven/BlogClient#1]
弱弱问一句这是什么～～

**Comment by cosven** [comment]
这个基本废弃了，一开始学习PyQt的时候，想写一个博客的本地客户端。

本来的想法是这样的：比如说，你可以从Oschina（开源中国）把自己的博客同步下来。或者可以在本地写博客，直接发布到Oschina上去，后来发现由于OSchina API的局限性。比如说：它API获取到的博客信息中不包含“博客最后一次更改的时间”，导致一些功能没办法再做下去。所以就抛弃了。

我记得项目当前进度是刚好完成了一个粗略的所见即所得的编辑器 （比较low）

**Comment by catbb49294929** [comment]
谢谢
